/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "type": string;
    }
    interface PocButton {
        "appearance": string;
        "text": string;
    }
    interface PocCard {
        "text": string;
    }
    interface PocInput {
        "placeholder": string;
        "type": string;
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPocButtonElement extends Components.PocButton, HTMLStencilElement {
    }
    var HTMLPocButtonElement: {
        prototype: HTMLPocButtonElement;
        new (): HTMLPocButtonElement;
    };
    interface HTMLPocCardElement extends Components.PocCard, HTMLStencilElement {
    }
    var HTMLPocCardElement: {
        prototype: HTMLPocCardElement;
        new (): HTMLPocCardElement;
    };
    interface HTMLPocInputElement extends Components.PocInput, HTMLStencilElement {
    }
    var HTMLPocInputElement: {
        prototype: HTMLPocInputElement;
        new (): HTMLPocInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "poc-button": HTMLPocButtonElement;
        "poc-card": HTMLPocCardElement;
        "poc-input": HTMLPocInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "type"?: string;
    }
    interface PocButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface PocCard {
        "text"?: string;
    }
    interface PocInput {
        "placeholder"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "poc-button": PocButton;
        "poc-card": PocCard;
        "poc-input": PocInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "poc-button": LocalJSX.PocButton & JSXBase.HTMLAttributes<HTMLPocButtonElement>;
            "poc-card": LocalJSX.PocCard & JSXBase.HTMLAttributes<HTMLPocCardElement>;
            "poc-input": LocalJSX.PocInput & JSXBase.HTMLAttributes<HTMLPocInputElement>;
        }
    }
}
